packages:
  - apps/*
  - apps/native-kmp/webview-scripts
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
  spawn-sync: true
  vue-demi: true
  workerd: true

catalog:
  '@better-auth/passkey': ^1.6.11
  '@changesets/cli': ^2.31.0
  '@simplewebauthn/server': 13.3.0
  "@types/node": ^24
  better-auth: ^1.6.11
  next-themes: ^0.4.6
  portless: ^0.13.0
  sonner: ^2.0.7
  typescript: ^6
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.21
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
