name: Deploy Worker
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - run: pnpm install

      - name: Deploy to dev
        if: github.ref == 'refs/heads/dev'
        run: pnpm run deploy:dev

      - name: Deploy to prod
        if: github.ref == 'refs/heads/main'
        run: pnpm run deploy:prod
